---
- name: Installing and Launch Filebeat
  hosts: webservers
  become: yes
  tasks:

  - name: Download filebeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat>

  - name: Install filebeat deb
    command: dpkg -i filebeat-7.4.0-amd64.deb

  - name: Copy from Ansible to WebVM yaml
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: Enable and Set Up filebeat
    command: filebeat modules enable system

  - name: Set Up filebeat
    command: filebeat setup

  - name: Start filebeat Service
    command: service filebeat start

  - name: Enable filebeat on Boot
    systemd:
      name: filebeat
      enabled: yes
